"""Модуль константы."""

SIZE_TAG_FIELDS = 32
SIZE_INGREDIENT_NAME_FIELD = 128
SIZE_UNIT_FIELD = 64
SIZE_RECIPE_NAME_FIELD = 128
MIN_AMOUNT_VALUE = 1
MIN_TIME_COOK_VALUE = 1
SIZE_EMAIL_FIELD = 254
SIZE_USERNAME_FIELD = 150
SIZE_FIRSTNAME_FIELD = 150
SIZE_LASTNAME_FIELD = 150